spring.application.name=movie-platform-api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/realistic_user?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Kavindye@SLIITit25100576

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.frontend.origin=*
